"""Generate JSON Schema and TypeScript from the Pydantic contracts.

Run with ``make contracts``. The generated files are committed so the web app
type-checks without a Python toolchain, and CI re-runs this to prove they are
in sync.
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path
from typing import Any

from pydantic import BaseModel

from saas_contracts import (
    AgentRunRead,
    BuildRouteInput,
    Event,
    Itinerary,
    Place,
    PlaceDetails,
    PlanCreate,
    PlanList,
    PlanRead,
    PlanStopCreate,
    PlanStopRead,
    PlanUpdate,
    Route,
    SavePlanOutput,
    SearchEventsInput,
    SearchEventsOutput,
    SearchPlacesInput,
    SearchPlacesOutput,
)
from saas_contracts.streaming import AgentEvent, ProgressStage

ROOT = Path(__file__).parent
GENERATED = ROOT / "generated"

MODELS: list[type[BaseModel]] = [
    AgentRunRead,
    BuildRouteInput,
    Event,
    Itinerary,
    Place,
    PlaceDetails,
    PlanCreate,
    PlanList,
    PlanRead,
    PlanStopCreate,
    PlanStopRead,
    PlanUpdate,
    Route,
    SavePlanOutput,
    SearchEventsInput,
    SearchEventsOutput,
    SearchPlacesInput,
    SearchPlacesOutput,
]

BANNER = (
    "// Generated by packages/contracts/generate.py — do not edit by hand.\n"
    "// Regenerate with: make contracts\n"
)


def build_json_schema() -> dict[str, Any]:
    """Emit one bundled schema so the TypeScript generator produces one file."""
    schema: dict[str, Any] = {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "title": "SaaSContracts",
        "type": "object",
        "properties": {},
        "$defs": {},
    }

    for model in MODELS:
        model_schema = model.model_json_schema(ref_template="#/$defs/{model}")
        defs = model_schema.pop("$defs", {})
        schema["$defs"].update(defs)
        schema["$defs"][model.__name__] = model_schema
        schema["properties"][model.__name__] = {"$ref": f"#/$defs/{model.__name__}"}

    return schema


# Keys whose values are *maps of name → schema*, not schemas themselves. The
# walk must recurse into their values without treating their keys as keywords.
_SCHEMA_MAPS = frozenset({"properties", "$defs", "definitions", "patternProperties"})

# Keys whose values are a schema or a list of schemas.
_SCHEMA_VALUES = frozenset(
    {"items", "additionalProperties", "not", "if", "then", "else", "contains"}
)
_SCHEMA_LISTS = frozenset({"anyOf", "oneOf", "allOf", "prefixItems"})

# Stripped from the TypeScript input only. `title` on a field schema becomes a
# spurious top-level type alias, and `maxItems` expands an array into a union of
# tuple types. The canonical schema.json keeps both.
_STRIP_KEYWORDS = frozenset({"title", "maxItems", "minItems"})


def simplify_for_typescript(schema: Any, *, keep_title: bool = True) -> Any:
    """Strip schema metadata that produces unusable TypeScript.

    Schema-aware rather than a blind recursive walk: a naive version deletes the
    *property* named "title" along with the "title" keyword, because inside a
    ``properties`` map the two are indistinguishable by key alone.

    ``keep_title`` is True for named definitions, whose title becomes the
    generated interface name, and False for field schemas.
    """
    if isinstance(schema, list):
        return [simplify_for_typescript(item, keep_title=False) for item in schema]

    if not isinstance(schema, dict):
        return schema

    result: dict[str, Any] = {}
    for key, value in schema.items():
        if key in _STRIP_KEYWORDS and not (key == "title" and keep_title):
            continue

        if key in _SCHEMA_MAPS and isinstance(value, dict):
            # Recurse into the values; the keys are names, never keywords.
            result[key] = {
                name: simplify_for_typescript(sub, keep_title=(key != "properties"))
                for name, sub in value.items()
            }
        elif key in _SCHEMA_LISTS and isinstance(value, list):
            result[key] = [simplify_for_typescript(item, keep_title=False) for item in value]
        elif key in _SCHEMA_VALUES:
            result[key] = simplify_for_typescript(value, keep_title=False)
        else:
            result[key] = value

    return result


def _ts_enum(name: str, values: list[str]) -> str:
    members = "\n".join(f'  {value.upper()} = "{value}",' for value in values)
    return f"export enum {name} {{\n{members}\n}}\n"


def write_typescript(schema: dict[str, Any]) -> Path:
    """Convert the JSON Schema to TypeScript with json-schema-to-typescript."""
    output = GENERATED / "index.ts"

    ts_input = GENERATED / ".schema.ts-input.json"
    ts_input.write_text(json.dumps(simplify_for_typescript(schema), indent=2, sort_keys=True))

    result = subprocess.run(  # noqa: S603
        [
            "pnpm",
            "--silent",
            "dlx",
            "json-schema-to-typescript@15",
            "--unreachableDefinitions",
            "--no-additionalProperties",
            "--bannerComment",
            "",
            str(ts_input),
        ],
        capture_output=True,
        text=True,
        cwd=ROOT,
        check=False,
    )

    if result.returncode != 0:
        print(result.stderr, file=sys.stderr)
        raise SystemExit(
            "TypeScript generation failed. Is pnpm installed? "
            "Install it with: corepack enable pnpm"
        )

    ts_input.unlink(missing_ok=True)

    body = result.stdout
    enums = "\n".join(
        [
            _ts_enum("AgentEvent", [e.value for e in AgentEvent]),
            _ts_enum("ProgressStage", [e.value for e in ProgressStage]),
        ]
    )

    output.write_text(f"{BANNER}\n{body.strip()}\n\n{enums}")
    return output


def main() -> None:
    schema = build_json_schema()
    GENERATED.mkdir(parents=True, exist_ok=True)

    schema_path = GENERATED / "schema.json"
    schema_path.write_text(json.dumps(schema, indent=2, sort_keys=True) + "\n")

    ts_path = write_typescript(schema)
    print(f"wrote {schema_path.relative_to(ROOT.parent.parent)}")
    print(f"wrote {ts_path.relative_to(ROOT.parent.parent)}")


if __name__ == "__main__":
    main()
